#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

if ! make test 2>&1 ; then
    echo "111Error while testing the code"
    exit 1
fi

exit 0